upstreams:
  core_banking:    "http://titan-core-banking:8080"
  notification:    "http://titan-notifications-service:8084"
  promotion:       "http://titan-promotions-service:8083"
  ai_service:      "http://titan-edge-ai:8001"

auth:
  jwt_secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"

rate_limit:
  requests_per_second: 100

server:
  port: 8088
