apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titan-banking-ingress
  namespace: titan-banking
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: titan-banking.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: titan-gateway
            port:
              number: 8000
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
