# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: risk_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'risk_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11risk_engine.proto\x12\x0brisk_engine\"3\n\x10RiskCheckRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"K\n\x11RiskCheckResponse\x12\x12\n\nrisk_score\x18\x01 \x01(\x05\x12\x12\n\nrisk_level\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t2_\n\x11RiskEngineService\x12J\n\tCheckRisk\x12\x1d.risk_engine.RiskCheckRequest\x1a\x1e.risk_engine.RiskCheckResponseB\x18\n\x14\x63om.titan.riskengineP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'risk_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.titan.riskengineP\001'
  _globals['_RISKCHECKREQUEST']._serialized_start=34
  _globals['_RISKCHECKREQUEST']._serialized_end=85
  _globals['_RISKCHECKRESPONSE']._serialized_start=87
  _globals['_RISKCHECKRESPONSE']._serialized_end=162
  _globals['_RISKENGINESERVICE']._serialized_start=164
  _globals['_RISKENGINESERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
