server.port=2020
spring.application.name=titan-event-consumer

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=titan-event-consumer-group
spring.kafka.security.protocol=PLAINTEXT
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
