server.port=8086

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=titan-cbs-adapter-group
spring.kafka.security.protocol=PLAINTEXT
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Legacy System Configuration
legacy.service.url=http://localhost:9099
legacy.service.timeout=5000

# Logging
logging.level.com.titan.adapter=DEBUG

# DTN / LTP Configuration
dtn.bundle.ttl-seconds=7200
dtn.bundle.store-path=./dtn-store

# Spring Boot Banner
spring.main.banner-mode=off
