server.port=9099
spring.mvc.contentnegotiation.media-types.application=application/xml

# Force XML content negotiation
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.ignore-accept-header=false
